### ISSUE TITLE
[Bug]: Service page is not responsive

### ISSUE THREAD

**Issue by srivishnu2805** [Open-Code-Crafters/FitFlex#399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The service page is not responsive on mobile and the Contact Us section needs to be improvised.

### Expected behavior

the service page should be responsive and the alignments should be done properly to the contact us section 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a6ff4414-3aff-4fc8-90e4-3de47276b82b)
![image](https://github.com/user-attachments/assets/a7957a34-15f0-4829-9cdd-ef581df2992b)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have updated the Services.jsx file to improve the responsiveness of the service page and enhance the Contact Us section. The changes include adjusting the layout for mobile devices, improving the alignment of elements, and refining the modal for better user experience. Here's a summary of the key changes:

1. Added responsive styling for the service cards and grid layout.
2. Improved the modal design and made it responsive for different screen sizes.
3. Enhanced the stats section layout and styling for better readability on mobile devices.
4. Adjusted the overall padding and margins for a more consistent look across devices.
5. Implemented a responsive design for the Contact Us form within the modal.

I also created pull request: https://github.com/Open-Code-Crafters/FitFlex/pull/400


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission
